python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat F --num_th 5 --dz 20
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat F --num_th 10 --dz 20
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat F --num_th 20 --dz 20
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat F --num_th 50 --dz 20
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat F --num_th 20 --dz 1
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat F --num_th 20 --dz 10
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat F --num_th 20 --dz 50
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat F --num_th 20 --dz 100
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat G --num_th 5 --dz 20
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat G --num_th 10 --dz 20
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat G --num_th 20 --dz 20
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat G --num_th 50 --dz 20
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat G --num_th 20 --dz 1
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat G --num_th 20 --dz 10
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat G --num_th 20 --dz 50
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat G --num_th 20 --dz 100
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_2 --num_th 10 --dz 10  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_3 --num_th 20 --dz 10  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_4 --num_th 50 --dz 10  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_5 --num_th 5 --dz 20  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_6 --num_th 10 --dz 20  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_7 --num_th 20 --dz 20  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_8 --num_th 50 --dz 20  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_9 --num_th 5 --dz 50  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_10 --num_th 10 --dz 50  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_11 --num_th 20 --dz 50  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_12 --num_th 50 --dz 50  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_13 --num_th 5 --dz 100  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_14 --num_th 10 --dz 100  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_15 --num_th 20 --dz 100  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_16 --num_th 50 --dz 100  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_17 --num_th 5 --dz 200  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_18 --num_th 10 --dz 200  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_19 --num_th 20 --dz 200  
python main_CMI_Est.py --mimic mi_diff --tester Neural --metric f_divergence --cat Non-lin-NI_20 --num_th 50 --dz 200